DELETE FROM users;
DELETE FROM posts;
DELETE FROM likes;
DELETE FROM history;
DELETE FROM comments;
DELETE FROM notifications;
DELETE FROM post_reports;
DELETE FROM comment_reports;
DELETE FROM admins;